<template>
  <div class="panels">
    <ul class="diary ">.
      <li class="action">
        <span>|</span>
        <span>最热日记</span>
      </li>
      <li>
        <span>|</span>
        <span>最新回复</span>
      </li>
      <li>
        <span>|</span>
        <span>最新日记</span>
      </li>
      <li>
        <span>|</span>
        <span>诊断报告优先</span>
      </li>
    </ul>
    <div class="project">
      <div class="first_project">
        <ul class="first content">
          <li class="action">
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
        </ul>
      </div>
      <div class="second_project">
        <ul class="second content">
          <li class="action">
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
        </ul>
      </div>
      <div class="third_project">
        <ul class="third content">
          <li class="action">
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
        </ul>
      </div>
    </div>
    <div class="region">
      <ul class="first content">
          <li class="action">
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          <li>
            <span>|</span>
            <span>最热日记</span>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
          </li>
          <li>
            <span>|</span>
            <span>最新回复</span>
          </li>
          <li>
            <span>|</span>
            <span>最新日记</span>
          </li>
          <li>
            <span>|</span>
            <span>诊断报告优先</span>
          </li>
      </ul>
    </div>
  </div>
</template>

<script type="text/ecmascript-6">
  import BScroll from 'better-scroll'
  export default {
    mounted(){
      new BScroll('.first_project', {
        // pullUpLoad: true
        scrollY: true
      })
      new BScroll('.second_project', {
        // pullUpLoad: true
        scrollY: true
      })
      new BScroll('.third_project', {
        // pullUpLoad: true
        scrollY: true
      })
    }
  }
</script>

<style lang="stylus" rel="stylesheet/stylus">
  .panels
    // display none
    position fixed
    width 100%
    bottom 0
    top 173px
    left 0
    z-index 10
    background #fff
    .diary
      display none 
      li
        height 89px
        line-height 89px
        padding-bottom 1px
        overflow hidden
        font-size 24px
        padding 0 26px
        &.action
          color #2cc7c5
    .project
      // display none
      display flex
      justify-content space-around
      background #fff
      overflow hidden
      .first_project
        height calc(100vh - 173px)
        position relative
        width 100%
        ul
          width 100%
          display flex
          flex-direction column
          position absolute
          li
            height 89px
            line-height 89px
            padding-bottom 1px
            overflow hidden
            font-size 24px
            padding 0 26px
            &.action
              color #2cc7c5
      .second_project
        height calc(100vh - 173px)
        position relative
        width 100%
        ul
          width 100%
          display flex
          flex-direction column
          position absolute
          li
            height 89px
            line-height 89px
            padding-bottom 1px
            overflow hidden
            font-size 24px
            padding 0 26px
            &.action
              color #2cc7c5
      .third_project
        height calc(100vh - 173px)
        position relative
        width 100%
        ul
          width 100%
          display flex
          flex-direction column
          position absolute
          li
            height 89px
            line-height 89px
            padding-bottom 1px
            overflow hidden
            font-size 24px
            padding 0 26px
            &.action
              color #2cc7c5
</style>
